language: emacs-lisp

script:
  - evm install $EVM_EMACS --use --skip
  - emacs --version
  - cask install
  - make test

env:
  matrix:
    - EVM_EMACS=emacs-24.4-travis
matrix:
  fast_finish: true

before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh

notifications:
  email: false
