version: 2.1

aktion:
  echo "Gebe Umgebung aus"
  ls -lart

jobs:
  opemode:
    docker:
      # - image: ubuntu-2004:202010-01
      - image: silex/emacs:27.2
    working_directory: ~/operator-mode
    steps:
      - run: apt update && apt install -y git ssh emacs
      - checkout
      - run:
          name: Umgebung
          command:
            echo "Gebe Umgebung aus"; ls -lart

      - run:
          name: ERT tests
          command: |
            emacs -Q --batch \
            --eval "(message (emacs-version))" \
            --eval "(message (getenv \"PWD\"))" \
            --eval "(load \"operator-mode.el\")" \
            --eval "(setq operator-mode-debug nil)" \
            --eval "(setq python-indent-offset 4)" \
            --eval "(setq python-indent-guess-indent-offset nil)" \
            --eval "(setq python-indent-guess-indent-offset-verbose nil)" \
            --eval "(load \"/root/operator-mode/test/operator-setup-tests.el\")\" \
            --eval \"(load \"/root/operator-mode/test/operator-python-mode-test.el\")\" \
            --eval \"(load \"/root/operator-mode/test/operator-other-test.el\")\" \
            --eval \"(load \"/root/operator-mode/test/operator-haskell-mode-test.el\")\" \
            --eval \"(sit-for 1)\" \
            -f ert-run-tests-batch-and-exit


workflows:
  opemode-workflow:
    jobs:
      - opemode
