version: 2.1

jobs:
  build:
    docker:
      - image: silex/emacs:27.2
    working_directory: /operator-mode
    steps:
      - run:
          name: ERT tests
          command: |
            emacs -Q --batch --eval \"(message (emacs-version))\"
