version: 2.1

jobs:
  opemode:
    docker:
      # - image: ubuntu-2004:202010-01
      - image: silex/emacs:27.2
    working_directory: ~/operator-mode
    steps:
      - run: apt update && apt install -y git ssh emacs
      - checkout
      - run:
          name: Umgebung
          command: |
            echo "Gebe Umgebung aus" 
            ls -lart
      - run:
          name: ERT tests
          command: |
            emacs -Q --batch \
            --eval "(message (emacs-version))" \
            --eval "(message (getenv \"PWD\"))"
            #  --eval "(load (expand-file-name \"/operator-mode/operator-mode.el\"))"

workflows:
  opemode-workflow:
    jobs:
      - opemode  
