version: 2.1

steps: &steps
  working_directory: /operator-mode
  steps:
    - run:
        name: ERT tests
        command: |
          test-startup.sh

jobs:
  emacs-27:
    docker:
      - image: silex/emacs:27.2
    <<: *steps
  emacs-26:
    docker:
      - image: silex/emacs:26.3
    <<: *steps
  emacs-25:
    docker:
      - image: silex/emacs:25.3
    <<: *steps

workflows:
  version: 2
  build:
    jobs:
      - emacs-25
      - emacs-26
      - emacs-27

