version: 2.1

jobs:
  build:
    docker:
      - image: silex/emacs:27.2
    working_directory: /
    steps:
      - run:
          name: ERT tests
          command: |
            emacs -Q --batch \
            --eval "(message (emacs-version))" \
            --eval "(message (getenv \"PWD\"))" \
            --eval "(load (expand-file-name \"operator-mode.el\"))"
