version: 2.1

steps: &steps
  working_directory: /operator-mode
  steps:
    - run:
        name: ERT tests
        command: |
          emacs -Q --batch -l .circleci/provide.el --funcall make-ert

    - run:
        name: Compile
        command: |
          emacs -Q --batch -l .circleci/provide.el --funcall make-compile operator-mode.el

    - run:
        name: Lint
        command: |
          emacs -Q --batch -l .circleci/provide.el --funcall make-lint operator-mode.el

jobs:
  emacs-27:
    docker:
      - image: silex/emacs:27.2
    <<: *steps
  emacs-26:
    docker:
      - image: silex/emacs:26.3
    <<: *steps
  emacs-25:
    docker:
      - image: silex/emacs:25.3
    <<: *steps

workflows:
  version: 2
  build:
    jobs:
      - emacs-25
      - emacs-26
      - emacs-27
